name: My JavaScript Action
description: Una acción personalizada en JavaScript para mi repositorio

inputs:
  my-input:
    description: 'Un ejemplo de entrada'
    required: true
    default: 'valor predeterminado'

runs:
  using: 'node12'
  main: 'ruta/al/entrypoint.js'
