name: Python CI

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"  # Ejecutar todos los domingos a medianoche

  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña de Acciones
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Reference the major version of a release
      - uses: actions/checkout@v4
      # Reference a specific version
      - uses: actions/checkout@v4.2.0
      # Reference a branch
      - uses: actions/checkout@main
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ejecutar script de Python
      - name: Run script
        run: |
          cd ReadmeGenerator
          python main.py
          cd ..
          using: node20

      # Configurar Git
      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --global --add safe.directory /github/workspace

      # Commit de cambios
      - name: Commit changes
        run: |
          git add -A
          git commit -m 'Deploy' || echo "No changes to commit"

      # Push de cambios a la rama main
      - name: Push changes to main
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
