name: CI

on:
  push:
    branches: [master, main]
  schedule:
    - cron: "5 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Aquí puedes especificar la versión de Node.js que desees, por ejemplo, '16' para Node.js 16.x

      - name: Generate static files
        run: '|
          cd ReadmeGenerator
          pip install -r requirements.txt
          python main.py
          cd ..'

      - name: Commit changes
        run: |
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy' 
          git config --global --add safe.directory /github/workspace

      - name: Force push to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          directory: ./

      - name: Force push to main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          directory: ./
